src:
  host: "103.160.75.28"
  port: 5432
  user: "orchai_rw"
  password: "travaorchai_rw123"
  database: "orchai"
  table: "public.validator_block"
dest:
  host: "103.160.75.28"
  port: 5432
  user: "orchai_rw"
  password: "travaorchai_rw123"
  database: "orchai"
  table: "public.block_label"
  batchsize: 1000
hp:
  etl:
    accept_rate: 0.1
    concentration_level: 0.9
    vote_score: 2
    propose_score: 6
    A: 9
    B: 4
    C: 2
    D: 4
    vote_proposed_win_size: 14400  
    combine_win_size: 150  
    label_win_size: 100800 
  upload:
    batch_size: 1999
