from:
  host: "103.160.75.28"
  port: 5432
  user: "orchai_rw"
  password: "travaorchai_rw123"
  database: "orchai"
  # table: "public.validator_block"
  table: "(select * from public.validator_block order by block_height limit 100000) as t"
to:
  host: "127.0.0.1"
  port: 5432
  user: "postgres"
  password: "dbadmin"
  database: "orchai"
  table: "validator_score"
  batchsize: 1000
