src:
  host: "103.160.75.28"
  port: 5432
  user: "orchai_rw"
  password: "travaorchai_rw123"
  database: "orchai"
  # table: "public.validator_block"
  table: "(select * from public.validator_block where block_height >= 7050501 and block_height <= 7052499 order by block_height) as t"
dest:
  host: "127.0.0.1"
  port: 5432
  user: "postgres"
  password: "dbadmin"
  database: "orchai"
  table: "block_label"
  batchsize: 1000
hp:
  etl:
    accept_rate: 0.1
    concentration_level: 0.9
    vote_score: 2
    propose_score: 6
    A: 9
    B: 4
    C: 2
    D: 4
    vote_proposed_win_size: 500 
    combine_win_size: 20 
    label_win_size: 60
  upload:
    batch_size: 1999
