db:
  host: "103.160.75.28"
  port: 5432
  user: "orchai_reader"
  password: "orchai_reader123"
  database: "orchai"
  table: "(select * from public.validator_block order by block_height limit 50000) as t"

 s